# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/services/service_frontend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/services/service_api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/services/service_daemon"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/services/service_device"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/services/service_environment"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/services/service_speak"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/services/service_user"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/services/common"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/setup/migrations"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/tests"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
